version: '1'
services:
  main:
    build: .
    image: opuscapita/servicenow-integration
    depends_on:
      - mysql
      - consul
      - registrator
      - redis
    volumes:
      - .:/home/node/servicenow-integration
    labels:
      SERVICE_NAME: 'servicenow-integration'
    extra_hosts:
      - 'consul:${HOST_IP}'
    environment:
      PORT: ${PORT}
      HOST_IP: ${HOST_IP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
      - '${PORT}:${PORT}'
    command: 'npm run dev'

  mysql:
    image: 'mysql:5.6'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - registrator

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ['consul://${HOST_IP}:8500']

  redis:
    image: ocbesbn/redis:latest
    ports:
      - '6379:6379'
    environment:
      REDIS_AUTH: ${REDIS_AUTH}
    depends_on:
      - registrator

  consul:
    image: consul:latest
    network_mode: host
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap-expect=1', '-bind=${HOST_IP}', '-client=0.0.0.0']
