#%RAML 1.0 ExampleSpec
{
  "sys_id":"1106d9120ff54b009368f88ce1050e8f",
  "table":"u_event",
  "display_name":"number",
  "display_value":"EVM1326167",
  "status":"inserted",
  "incident" : "OCIN0123456"
}
