#%RAML 1.0
title: ServiceNow Integration
description: API to create tickets inside servicenow
version: 1.0.0
baseUri: http://localhost:3016
types:
  errormessage:
    type: object
    properties:
      error: string
    example: !include examples/errormessage.raml
  servicenow-post:
    type: object
    properties:
      shortdesc:
        type: string
        required:  true
      longdesc:
        type: string
        required: true
      prio:
        description: priority of the created ticket
        type: number
        required: true
        minimum: 1
        maximum: 3
      customer:
        type: string
        required: true
      service:
        type: string
        required: true
      assignmentgroup:
        type: assignmentgroup
        required: true
      ciid:
        type: string
        required: false
    example: !include examples/servicenow-post.raml
  assignmentgroup:
    type: string
    description: group that will be mapped to servicenow assignmentgroup
    enum: plattform
  servicenow-response:
    type: object
    properties:
      sys_id: string
      table: string
      display_name: string
      display_value:
        type: string
        description: EVN-numer of the created event-ticket
      status: string
      incident:
        type: string
        description: OCIN-number of the created incident-ticket
    example: !include examples/servicenow-response.raml
/api/insert:
  post:
    body:
      application/json:
        type: servicenow-post
    responses:
      200:
        body:
          application/json:
            type: servicenow-response
      500:
        body:
          application/json:
            type: errormessage
/api/health-checks:
  get:
    responses:
      200:
          body:
            application/json:
              type: servicenow-response[]
      500:
        body:
          application/json:
            type: errormessage
